#!/bin/bash
set -e
cd "$(dirname "$0")"

echo "Building ecmCouplingFunctionObjects..."
wmake libso src/ecmCouplingFunctionObjects
echo "Done."

echo "Building ecmFvOptions..."
wmake libso src/ecmFvOptions
echo "Done."

echo "Building ecmPatchFields..."
wmake libso src/ecmPatchFields
echo "Done."

echo "Building chtMultiRegionSolidFoam..."
wmake src/chtMultiRegionSolidFoam
echo "Done."
