@echo off
REM ============================================================
REM  ECM Coupler — one-time setup for STAR-CCM+ 21.02
REM  Run this ONCE from the package folder before opening STAR.
REM ============================================================

setlocal EnableDelayedExpansion

echo.
echo === ECM Coupler Setup ===
echo.

REM ----------------------------------------------------------
REM 1. Locate Python
REM ----------------------------------------------------------
set PYTHON=

REM Try py launcher first (standard Windows Python installer)
where py >nul 2>&1
if %ERRORLEVEL%==0 (
    set PYTHON=py
    goto :found_python
)

REM Try python3
where python3 >nul 2>&1
if %ERRORLEVEL%==0 (
    set PYTHON=python3
    goto :found_python
)

REM Try python
where python >nul 2>&1
if %ERRORLEVEL%==0 (
    REM Make sure it's not the Windows Store stub
    python --version >nul 2>&1
    if %ERRORLEVEL%==0 (
        set PYTHON=python
        goto :found_python
    )
)

echo [ERROR] Python not found on PATH.
echo         Install Python 3.9+ from https://python.org and re-run this script.
pause
exit /b 1

:found_python
echo [OK] Python found: %PYTHON%
%PYTHON% --version

REM ----------------------------------------------------------
REM 2. Install Python dependencies
REM ----------------------------------------------------------
echo.
echo Installing Python dependencies (numpy, pandas)...
%PYTHON% -m pip install --quiet numpy pandas
if %ERRORLEVEL% neq 0 (
    echo [ERROR] pip install failed. Check your Python/pip installation.
    pause
    exit /b 1
)
echo [OK] Dependencies installed.

REM ----------------------------------------------------------
REM 3. Patch ECM_COMMAND in config.properties with found Python
REM ----------------------------------------------------------
echo.
echo Writing config.properties...
(
    echo # Auto-generated by setup.bat — edit if needed
    echo python=%PYTHON%
    echo ecm_script=ecm\ecm_coupler.py
    echo ecm_in=ecm\ecm_in.bin
    echo ecm_out=ecm\ecm_out.bin
) > config.properties
echo [OK] config.properties written.

REM ----------------------------------------------------------
REM 4. Smoke-test the ECM backend
REM ----------------------------------------------------------
echo.
echo Running ECM smoke test...
%PYTHON% ecm\ecm_coupler.py --help >nul 2>&1
if %ERRORLEVEL%==0 (
    echo [OK] ECM backend responds.
) else (
    echo [WARN] ECM backend --help returned non-zero. This may be normal.
)

REM ----------------------------------------------------------
REM 5. Print next steps
REM ----------------------------------------------------------
echo.
echo ============================================================
echo  Setup complete.
echo.
echo  Next steps in STAR-CCM+:
echo    1. Open your .sim file
echo    2. One-time wiring (first run only):
echo       a. Tools ^> Global Parameters ^> New Scalar
echo          Name: ecmQdot_W_m3    Value: 0   Units: W/m^3
echo       b. Regions ^> jellyRoll ^> Physics Values ^>
echo          Volumetric Heat Source ^> Method: Field Function
echo          Function definition: $ecmQdot_W_m3
echo    3. Tools ^> Macros ^> Run Macro ^> EcmCouplerMacro.jar
echo       (do NOT press the Run button — the macro drives the solver)
echo ============================================================
echo.
pause
